### ISSUE TITLE
badger2040/docs/reference.md - the  [PicoGraphics function reference] link is broken

### ISSUE THREAD

**Issue by typxxi** [pimoroni/badger2040#18]
In the section Basic Drawing Settings you will find this broken link:

Since Badger 2040 is based upon PicoGraphics you should read the [PicoGraphics function reference](https://github.com/pimoroni/badger2040/blob/main/docs/%5B../picographics/README.md%5D(https:/github.com/pimoroni/pimoroni-pico/blob/main/micropython/modules/picographics/README.md)) for more information about how to draw to the display.

**Comment by helgibbons** [comment]
Thanks for the heads up - I've fixed the link.
