### ISSUE TITLE
SD Card / SPI for Badger 2040 W

### ISSUE THREAD

**Issue by niutech** [pimoroni/badger2040#3]
Is it possible to connect an SD Card to Badger 2040 W using the microSD card module and the SPI interface? If so, which pins can I use?

**Comment by Gadgetoid** [comment]
It looks like GPIO 0, 1, 2 and 3 are available which according to https://pico.pinout.xyz/ is a complete SPI bus, which should work with the micropython-lib SDCard driver (https://github.com/micropython/micropython-lib/blob/master/micropython/drivers/storage/sdcard/sdcard.py). This bus would be shared by the screen, though.

I don't know if there are any gotchas that might stop it from working, but it's worth a try.
