### ISSUE TITLE
I2C pins on Qwiic connector

### ISSUE THREAD

**Issue by jabbershort** [pimoroni/badger2040#46]
I'm trying to add a breakout board (BME688) via the Qwiic connector, however no combination of SDA/SCL pins can detect the board, what pins should I use to access boards via the connector?

**Comment by helgibbons** [comment]
Badgers use the standard Pico I2C pins for I2C - GP4 and GP5.

There's a basic example for BME68x that you could try here: 

https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/examples/breakout_bme68x/bme68x_demo.py

**Comment by jabbershort** [comment]
Hi @helgibbons, thanks for your response. I've just found out that hadn't worked for me because the Qwiic connector on my badger wasn't actually soldered to the board!

**Comment by helgibbons** [comment]
Sorry to hear that - drop us a line at support@pimoroni.com if you need a replacement sorting!
