### ISSUE TITLE
Badger example responds strangely

### ISSUE THREAD

**Issue by VaporwareII** [pimoroni/badger2040#47]
I just updated to 0.0.3 on a Badger2040 and attempted the "getting started" examples

```
>>> import badger2040
>>> badger = badger2040.Badger2040()
>>> print(badger2040.is_wireless)
<function is_wireless at 0x2000d120>
```
which is not the expected False value

everything else in the getting started seems to work as expected.  I tried reflashing the uf twice to see if something weird happened.

**Comment by helgibbons** [comment]
Try `print(badger2040.is_wireless())` !

(I'll just get that fixed up in the Learn article... 😅)

**Comment by helgibbons** [comment]
I've fixed this erroneous info, so closing this one for now :)
