### ISSUE TITLE
Bad link in the 2040W docs - setting up micropython md file isn't here.

### ISSUE THREAD

**Issue by simonprickett** [pimoroni/badger2040#5]
I would do a PR to fix this but not sure where the file is right now :)

On the page:

https://github.com/pimoroni/badger2040/tree/main/badger_os

There's a link `[Installing MicroPython](https://github.com/pimoroni/badger2040/setting-up-micropython.md)` but that file isn't in this repo.

**Comment by helgibbons** [comment]
Installation instructions are now covered in the [main readme of this repo](https://github.com/pimoroni/badger2040) and the [updated Learn guide](https://learn.pimoroni.com/article/getting-started-with-badger-2040), so closing this one for now :)
